-- 코드를 입력하세요
SELECT 
O.ANIMAL_ID,
O.NAME
FROM ANIMAL_OUTS O
LEFT JOIN ANIMAL_INS I USING(ANIMAL_ID)
WHERE I.ANIMAL_TYPE IS NULL AND I.DATETIME IS NULL AND I.INTAKE_CONDITION IS NULL AND I.NAME IS NULL AND I.SEX_UPON_INTAKE IS NULL