-- 코드를 입력하세요
SELECT
M.MEMBER_NAME, 
R.REVIEW_TEXT, 
DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
LEFT JOIN MEMBER_PROFILE M USING(MEMBER_ID)
WHERE R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM (
        SELECT 
            MEMBER_ID, 
            RANK() OVER(ORDER BY COUNT(*) DESC) AS RNK
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
    ) A
    WHERE RNK = 1
)
ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC;