-- 코드를 작성해주세요
SELECT
A.ID,
A.FISH_NAME,
A.LENGTH
FROM (
    SELECT 
    ID,  
    LENGTH, 
    FISH_NAME,
    RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RANKS
    FROM FISH_INFO
    JOIN FISH_NAME_INFO N USING(FISH_TYPE)
) A
WHERE RANKS = 1 AND LENGTH IS NOT NULL
ORDER BY ID ASC
