-- 코드를 작성해주세요

SELECT
SUM(SCORE) AS SCORE,
E.EMP_NO,
E.EMP_NAME,
E.POSITION,
E.EMAIL
FROM 
HR_GRADE G 
LEFT JOIN HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
ORDER BY SUM(SCORE) DESC
LIMIT 1